---
engines:
  fixme:
    enabled: true
  pmd:
    enabled: true
    channel: "beta"
  checkstyle:
    enabled: true
    channel: "beta"

ratings:
  paths:
  - "app/**/*"
  - "**.java"
exclude_paths: []
